### ISSUE TITLE
Enhance Quotation Module

### ISSUE THREAD

**Issue by erratumsolutions** [Erratums/ims-support#23]
- [x] Quotation should not adjust stock quantity by default 
- [x] Add a settings option, so that users can enable it to enable stock adjustment for quotation 
- [x] #46
- [ ] #24

**Comment by ajumalp** [comment]
> Quotation should not adjust stock quantity by default
Added a settings option under invoice as **Enable Stock for Quotation**
![image](https://user-images.githubusercontent.com/12585082/152672552-bd1a7f82-9ae6-4146-80ef-4abef5422a59.png)
