### ISSUE TITLE
Disable stock for Server Items 

### ISSUE THREAD

**Issue by erratumsolutions** [Erratums/ims-support#48]
### Disable stock for Server Items 
- [x] If **Product Type** is **Service** then **Enable Stock** should be `No` 
- [x] If **Product Type** is **Service** then hide fields related to stock [Enable Stock and Minimum Stock]
- [x] In Items List, color for items with type service should be primary [or something else]
- [x] The HSN Code should be renamed as SAC Code if type is service

**Comment by erratumsolutions** [comment]
SUCCESS color code is selected as it's nearest to product with stock is disabled

**Comment by ajumalp** [comment]
SUCCESS color code is selected as it's nearest to product with stock is disabled
